import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { authService } from '../services/authService';
import { Mail, ArrowLeft, ArrowRight, Brain, CheckCircle2, ShieldCheck, Lock, Eye, EyeOff, Hash } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

import emailjs from '@emailjs/browser';

const ForgotPassword = () => {
  const [step, setStep] = useState(1); // 1: Email, 2: OTP, 3: New Password, 4: Success
  const [email, setEmail] = useState('');
  const [otp, setOtp] = useState(['', '', '', '', '', '']);
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState(null);
  const [token, setToken] = useState('');
  const navigate = useNavigate();

  const handleEmailSubmit = async (e) => {
    e.preventDefault();
    setError(null);
    setIsSubmitting(true);
    const trimmedEmail = email.trim();

    try {
      console.log("Initiating password recovery for:", trimmedEmail);
      const data = await authService.forgotPassword(trimmedEmail);
      
      if (data.token) {
        const [jwt, serverOtp] = data.token.split('|');
        setToken(jwt);

        try {
          console.log("OTP generated by backend. Sending via EmailJS...");
          console.log("DEBUG: Your OTP code is", serverOtp);
          
          await emailjs.send(
            "service_xw4d9ms",
            "template_miux60i",
            {
              to_email: trimmedEmail,
              passcode: serverOtp,
              time: "15 minutes",
              email: trimmedEmail
            },
            {
              publicKey: "LmYCa_nsdjDcH3Vzm",
            }
          );
        } catch (emailErr) {
          console.error("EmailJS sending failed:", emailErr);
          setError(`Email service error: ${emailErr.text || 'Service unavailable'}. You can check the console for the code during testing.`);
        }

        setStep(2);
      } else {
        // For security, we still move to step 2 even if user is not found
        setStep(2);
      }
    } catch (err) {
      console.error("Forgot password request failed:", err);
      setError(err.message || 'Failed to initiate recovery.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleOtpChange = (index, value) => {
    if (isNaN(value)) return;
    const newOtp = [...otp];
    newOtp[index] = value.substring(value.length - 1);
    setOtp(newOtp);

    // Auto focus next
    if (value && index < 5) {
      const nextInput = document.getElementById(`otp-${index + 1}`);
      nextInput?.focus();
    }
  };

  const handlePaste = (e) => {
    e.preventDefault();
    const pastedData = e.clipboardData.getData('text').slice(0, 6).split('');
    const newOtp = [...otp];
    
    pastedData.forEach((char, index) => {
      if (index < 6 && !isNaN(char)) {
        newOtp[index] = char;
      }
    });
    
    setOtp(newOtp);
    // Focus the last filled input or the 6th input
    const nextIndex = Math.min(pastedData.length, 5);
    document.getElementById(`otp-${nextIndex}`)?.focus();
  };

  const handleOtpKeyDown = (index, e) => {
    if (e.key === 'Backspace' && !otp[index] && index > 0) {
      const prevInput = document.getElementById(`otp-${index - 1}`);
      prevInput?.focus();
    }
  };

  const handleVerifyOtp = (e) => {
    e.preventDefault();
    const otpValue = otp.join('');
    if (otpValue.length !== 6) {
      setError('Please enter the full 6-digit code.');
      return;
    }
    setStep(3);
  };

  const handleResetPassword = async (e) => {
    e.preventDefault();
    if (newPassword !== confirmPassword) {
      setError('Passwords do not match.');
      return;
    }
    if (newPassword.length < 8) {
      setError('Password must be at least 8 characters.');
      return;
    }

    setError(null);
    setIsSubmitting(true);

    try {
      const otpValue = otp.join('');
      await authService.resetPassword(token, otpValue, newPassword);
      setStep(4);
      setTimeout(() => navigate('/login'), 4000);
    } catch (err) {
      setError(err.message || 'Failed to reset password. Session may have expired.');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen mesh-gradient-theme flex font-poppins relative overflow-hidden">
      {/* Back to Login */}
      {step < 4 && (
        <button
          onClick={() => step > 1 ? setStep(step - 1) : navigate('/login')}
          className="absolute top-6 left-6 sm:top-8 sm:left-8 z-50 flex items-center gap-2 text-[var(--text-tertiary)] hover:text-[var(--text-primary)]   transition-all group p-2 bg-[var(--bg-surface)]  border border-[var(--border-default)]  backdrop-blur-md rounded-lg sm:bg-transparent sm:border-transparent sm: sm: shadow-sm sm:shadow-none"
        >
          <ArrowLeft size={18} className="group-hover:-translate-x-1 transition-transform" />
          <span className="text-[10px] sm:text-xs font-bold tracking-[0.25em] uppercase">
            {step === 1 ? 'Back to Login' : 'Previous Step'}
          </span>
        </button>
      )}

      <div className="w-full flex items-center justify-center p-4">
        <motion.div
          layout
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="w-full max-w-[460px] bg-[var(--bg-surface)]  backdrop-blur-2xl border border-[var(--border-default)]  p-8 sm:p-10 rounded-[40px] relative shadow-2xl transition-all duration-500"
        >
          <AnimatePresence mode="wait">
            {/* Step 1: Email */}
            {step === 1 && (
              <motion.div
                key="step1"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="space-y-8"
              >
                <div className="text-center">
                  <div className="flex justify-center mb-6">
                    <div className="w-16 h-16 bg-[var(--bg-surface)]  backdrop-blur-md border border-[var(--border-default)]  rounded-full flex items-center justify-center shadow-xl">
                      <Brain size={32} className="text-[var(--accent-primary)] " />
                    </div>
                  </div>
                  <h1 className="text-3xl font-black text-[var(--text-primary)]  tracking-tighter mb-2">
                    Identity <span className="text-[var(--accent-primary)]    dark:from-indigo-400 dark:to-purple-400">Recovery</span>
                  </h1>
                  <p className="text-[var(--text-tertiary)]  text-sm font-medium">Enter your email to receive a secure verification code.</p>
                </div>

                <form onSubmit={handleEmailSubmit} className="space-y-6">
                  {error && <div className="p-3 rounded-xl bg-[var(--color-danger-subtle)] border border-[var(--color-danger)] text-[var(--color-danger)]  text-xs font-bold uppercase tracking-wider text-center">{error}</div>}
                  
                  <div className="relative group">
                    <input
                      type="email"
                      required
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      className="peer w-full bg-[var(--bg-subtle)]  border border-[var(--border-default)]  rounded-2xl py-4 pl-12 pr-4 outline-none focus:ring-2 focus:ring-[var(--accent-primary-subtle)] focus:border-[var(--accent-primary)]/50 transition-all duration-300 font-medium text-[var(--text-primary)]  placeholder-transparent"
                      placeholder="Email Address"
                    />
                    <Mail className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400 peer-focus:text-[var(--accent-primary)] transition-colors duration-300" />
                    <label className="absolute left-12 top-2 text-[10px] font-bold text-[var(--text-tertiary)]  uppercase tracking-widest transition-all duration-300 peer-placeholder-shown:top-1/2 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:text-sm peer-placeholder-shown:font-medium peer-placeholder-shown:normal-case peer-focus:top-2 peer-focus:-translate-y-0 peer-focus:text-[10px] peer-focus:font-bold peer-focus:uppercase peer-focus:tracking-widest peer-focus:text-[var(--accent-primary)]  pointer-events-none">
                      Email Address
                    </label>
                  </div>

                  <button
                    type="submit"
                    disabled={isSubmitting}
                    className={`w-full relative group overflow-hidden px-8 py-4 bg-[var(--bg-base)]  rounded-2xl text-[var(--text-primary)]  font-bold text-sm uppercase tracking-widest shadow-2xl shadow-[var(--accent-primary-subtle)] transition-all duration-500 hover:-translate-y-1 hover:shadow-[var(--accent-primary-subtle)] ${isSubmitting ? 'opacity-70 pointer-events-none' : ''}`}
                  >
                    <span className="relative z-10 flex items-center justify-center gap-3">
                      {isSubmitting ? 'Sending...' : 'Get OTP Code'} {!isSubmitting && <ArrowRight size={20} className="group-hover:translate-x-1.5 transition-transform duration-300" />}
                    </span>
                    <div className="absolute inset-0 bg-gradient-to-r var(--gradient-brand) opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                  </button>
                </form>
              </motion.div>
            )}

            {/* Step 2: OTP */}
            {step === 2 && (
              <motion.div
                key="step2"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="space-y-8"
              >
                <div className="text-center">
                  <div className="flex justify-center mb-6">
                    <div className="w-16 h-16 bg-[var(--bg-surface)]  backdrop-blur-md border border-[var(--border-default)]  rounded-full flex items-center justify-center shadow-xl">
                      <Hash size={32} className="text-[var(--accent-primary)] " />
                    </div>
                  </div>
                  <h1 className="text-3xl font-black text-[var(--text-primary)]  tracking-tighter mb-2">
                    Verify <span className="text-[var(--accent-primary)]    dark:from-indigo-400 dark:to-purple-400">Identity</span>
                  </h1>
                  <p className="text-[var(--text-tertiary)]  text-sm font-medium">Enter the 6-digit code sent to <span className="text-[var(--accent-primary)] font-bold">{email}</span></p>
                </div>

                <form onSubmit={handleVerifyOtp} className="space-y-8">
                  {error && <div className="p-3 rounded-xl bg-[var(--color-danger-subtle)] border border-[var(--color-danger)] text-[var(--color-danger)]  text-xs font-bold uppercase tracking-wider text-center">{error}</div>}

                  <div className="flex justify-between gap-2">
                    {otp.map((digit, idx) => (
                      <input
                        key={idx}
                        id={`otp-${idx}`}
                        type="text"
                        maxLength="1"
                        value={digit}
                        onChange={(e) => handleOtpChange(idx, e.target.value)}
                        onKeyDown={(e) => handleOtpKeyDown(idx, e)}
                        onPaste={handlePaste}
                        className="w-12 h-14 sm:w-14 sm:h-16 text-center text-xl font-black bg-[var(--bg-subtle)]  border border-[var(--border-default)]  rounded-2xl focus:ring-2 focus:ring-[var(--accent-primary-subtle)] focus:border-[var(--accent-primary)]/50 outline-none transition-all text-[var(--text-primary)] "
                      />
                    ))}
                  </div>

                  <button
                    type="submit"
                    className="w-full relative group overflow-hidden px-8 py-4 bg-[var(--bg-base)]  rounded-2xl text-[var(--text-primary)]  font-bold text-sm uppercase tracking-widest shadow-2xl shadow-[var(--accent-primary-subtle)] transition-all duration-500 hover:-translate-y-1 hover:shadow-[var(--accent-primary-subtle)]"
                  >
                    <span className="relative z-10 flex items-center justify-center gap-3">
                      Verify Code <ArrowRight size={20} className="group-hover:translate-x-1.5 transition-transform duration-300" />
                    </span>
                    <div className="absolute inset-0 bg-gradient-to-r var(--gradient-brand) opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                  </button>

                  <p className="text-center text-[10px] font-black text-slate-400 uppercase tracking-widest">
                    Didn't get the code? <button type="button" onClick={handleEmailSubmit} className="text-[var(--accent-primary)] hover:underline">Resend</button>
                  </p>
                </form>
              </motion.div>
            )}

            {/* Step 3: New Password */}
            {step === 3 && (
              <motion.div
                key="step3"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="space-y-8"
              >
                <div className="text-center">
                  <div className="flex justify-center mb-6">
                    <div className="w-16 h-16 bg-[var(--bg-surface)]  backdrop-blur-md border border-[var(--border-default)]  rounded-full flex items-center justify-center shadow-xl">
                      <ShieldCheck size={32} className="text-[var(--accent-primary)] " />
                    </div>
                  </div>
                  <h1 className="text-3xl font-black text-[var(--text-primary)]  tracking-tighter mb-2">
                    Account <span className="text-[var(--accent-primary)]    dark:from-indigo-400 dark:to-purple-400">Security</span>
                  </h1>
                  <p className="text-[var(--text-tertiary)]  text-sm font-medium">Set your new secure access credentials.</p>
                </div>

                <form onSubmit={handleResetPassword} className="space-y-4">
                  {error && <div className="p-3 rounded-xl bg-[var(--color-danger-subtle)] border border-[var(--color-danger)] text-[var(--color-danger)]  text-xs font-bold uppercase tracking-wider text-center">{error}</div>}

                  <div className="relative group">
                    <input
                      type={showPassword ? "text" : "password"}
                      required
                      value={newPassword}
                      onChange={(e) => setNewPassword(e.target.value)}
                      className="peer w-full bg-[var(--bg-subtle)]  border border-[var(--border-default)]  rounded-2xl py-4 pl-12 pr-12 outline-none focus:ring-2 focus:ring-[var(--accent-primary-subtle)] focus:border-[var(--accent-primary)]/50 transition-all duration-300 font-medium text-[var(--text-primary)]  placeholder-transparent"
                      placeholder="New Password"
                    />
                    <Lock className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400 peer-focus:text-[var(--accent-primary)] transition-colors duration-300" />
                    <label className="absolute left-12 top-2 text-[10px] font-bold text-[var(--text-tertiary)]  uppercase tracking-widest transition-all duration-300 peer-placeholder-shown:top-1/2 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:text-sm peer-placeholder-shown:font-medium peer-placeholder-shown:normal-case peer-focus:top-2 peer-focus:-translate-y-0 peer-focus:text-[10px] peer-focus:font-bold peer-focus:uppercase peer-focus:tracking-widest peer-focus:text-[var(--accent-primary)]  pointer-events-none">
                      New Password
                    </label>
                    <button
                      type="button"
                      onClick={() => setShowPassword(!showPassword)}
                      className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 hover:text-[var(--accent-primary)] transition-colors focus:outline-none"
                    >
                      {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                    </button>
                  </div>

                  <div className="relative group">
                    <input
                      type={showPassword ? "text" : "password"}
                      required
                      value={confirmPassword}
                      onChange={(e) => setConfirmPassword(e.target.value)}
                      className="peer w-full bg-[var(--bg-subtle)]  border border-[var(--border-default)]  rounded-2xl py-4 pl-12 pr-12 outline-none focus:ring-2 focus:ring-[var(--accent-primary-subtle)] focus:border-[var(--accent-primary)]/50 transition-all duration-300 font-medium text-[var(--text-primary)]  placeholder-transparent"
                      placeholder="Confirm Password"
                    />
                    <Lock className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400 peer-focus:text-[var(--accent-primary)] transition-colors duration-300" />
                    <label className="absolute left-12 top-2 text-[10px] font-bold text-[var(--text-tertiary)]  uppercase tracking-widest transition-all duration-300 peer-placeholder-shown:top-1/2 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:text-sm peer-placeholder-shown:font-medium peer-placeholder-shown:normal-case peer-focus:top-2 peer-focus:-translate-y-0 peer-focus:text-[10px] peer-focus:font-bold peer-focus:uppercase peer-focus:tracking-widest peer-focus:text-[var(--accent-primary)]  pointer-events-none">
                      Confirm Password
                    </label>
                  </div>

                  <button
                    type="submit"
                    disabled={isSubmitting}
                    className={`w-full relative group overflow-hidden px-8 py-4 bg-[var(--bg-base)]  rounded-2xl text-[var(--text-primary)]  font-bold text-sm uppercase tracking-widest shadow-2xl shadow-[var(--accent-primary-subtle)] transition-all duration-500 hover:-translate-y-1 hover:shadow-[var(--accent-primary-subtle)] ${isSubmitting ? 'opacity-70 pointer-events-none' : ''}`}
                  >
                    <span className="relative z-10 flex items-center justify-center gap-3">
                      {isSubmitting ? 'Syncing...' : 'Reset Password'} {!isSubmitting && <ArrowRight size={20} className="group-hover:translate-x-1.5 transition-transform duration-300" />}
                    </span>
                    <div className="absolute inset-0 bg-gradient-to-r var(--gradient-brand) opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                  </button>
                </form>
              </motion.div>
            )}

            {/* Step 4: Success */}
            {step === 4 && (
              <motion.div
                key="step4"
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                className="text-center py-6"
              >
                <div className="flex justify-center mb-6">
                  <div className="w-20 h-20 bg-emerald-500/10 rounded-full flex items-center justify-center border border-emerald-500/20">
                    <CheckCircle2 size={40} className="text-emerald-500" />
                  </div>
                </div>
                <h2 className="text-3xl font-black text-[var(--text-primary)]  mb-4 tracking-tighter">Success!</h2>
                <p className="text-[var(--text-tertiary)]  text-sm leading-relaxed mb-8 font-medium">
                  Your identity has been verified and your password updated. Redirecting to login...
                </p>
                <div className="w-full h-1.5 bg-slate-100 /5 rounded-full overflow-hidden">
                  <motion.div
                    initial={{ width: 0 }}
                    animate={{ width: "100%" }}
                    transition={{ duration: 4 }}
                    className="h-full bg-gradient-to-r from-emerald-500 to-teal-400 shadow-[0_0_10px_rgba(16,185,129,0.5)]"
                  />
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </motion.div>
      </div>
    </div>
  );
};

export default ForgotPassword;
